Robot:
  Start:
    - [7, 7]

  Goal:
    - [8, 14]

Pedestrians:
  Positions:
    - [13.7, 7.7]
    - [12.5, 11.3]
    - [9.6, 13.5]
    - [5.8, 13.4]
    - [2.8, 11.3]
    - [1.6, 7.6]
    - [2.8, 4.1]
    - [5.8, 1.9]
    - [9.5, 2.0]
    - [12.6, 4.1]

Goals:
  Positions:
    - [1.6, 7.6]
    - [2.8, 4.1]
    - [5.8, 1.9]
    - [9.5, 2.0]
    - [12.6, 4.1]
    - [13.7, 7.7]
    - [12.5, 11.3]
    - [9.6, 13.5]
    - [5.8, 13.4]
    - [2.8, 11.3]