Robot:
  Start:
    - [5.8, 2.5]

  Goal:
    - [7.5, 13]

Pedestrians:
  Positions:
    - [0.5, 7.4]
    - [1.7, 4.0]
    - [3.5, 6.1]
    - [4.5, 4.8]
    - [5.8, 7.0]
    - [9.0, 10.5]
    - [8.2, 12.3]
    - [10.5, 11.8]
    - [11.0, 8.1]
    - [13.2, 10.7]

Goals:
  Positions:
    - [8.5, 5.2]
    - [10.0, 7.4]
    - [11.3, 4.5]
    - [13.2, 6.8]
    - [9.8, 4.1]
    - [0.5, 9.2]
    - [1.7, 11.3]
    - [4.0, 10.5]
    - [2.2, 7.8]
    - [3.5, 11.0]
