Robot:
  Start:
    - [7.8, 2.5]

  Goal:
    - [7.5, 13]

Pedestrians:
  Positions:
    - [0.4, 11.5]
    - [1.9, 12.3]
    - [0.4, 10.8]
    - [4.2, 13.1]
    - [1.6, 10.7]
    - [10.5, 10.75]
    - [12.6, 12.60]
    - [14.0, 11.75]
    - [13.2, 10.90]
    - [11.1, 11.95]

Goals:
  Positions:
    - [10.5, 2.45]
    - [12.6, 3.60]
    - [13.9, 0.75]
    - [11.2, 4.90]
    - [10.8, 1.95]
    - [0.9, 4.3]
    - [1.8, 2.7]
    - [3.4, 4.1]
    - [4.3, 2.5]
    - [2.1, 1.6]
